shared:
  project: stocks-455113
  T_etfs: etfs
  T_info: stock_info
  T_prices: stock_prices
  T_etfs2track: ETFS_to_track
dev:
  DS_raw: stocks_raw_dev
  DS_refined: stocks_refined_dev
  DS_user: stocks_user_data_dev
prod:
  DS_raw: stocks_raw
  DS_refined: stocks_refined
  DS_user: stocks_user_data