[gcp_service_account_viewer]
type = "?"
project_id = "?"
private_key_id = "?"
private_key = "?"
client_email = "?"
client_id = "?"
auth_uri = "?"
token_uri = "?"
auth_provider_x509_cert_url = "?"
client_x509_cert_url = "?"

[gcp_service_account_admin]
type = "?"
project_id = "?"
private_key_id = "?"
private_key = "?"
client_email = "?"
client_id = "?"
auth_uri = "?"
token_uri = "?"
auth_provider_x509_cert_url = "?"
client_x509_cert_url = "?"

[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
client_id = "?"
client_secret = "?"
cookie_secret = "?"
server_metadata_url = "?"

[security]
admins = ["?", "?"]

[global]
env = "dev"

